CONFIG_GPIO=y

CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_SUM_LOG=y

CONFIG_SENSOR=y
CONFIG_I2C=y

# UARTE1 and TWIM1 share the SERIAL1 hardware instance on the nRF5340.
# Disable TF-M secure logging so the non-secure application can use TWIM1/I2C1.
CONFIG_TFM_LOG_LEVEL_SILENCE=y
